### ISSUE TITLE
Not able to find curl executable

### ISSUE THREAD

**Issue by karanrajsingh** [relaxdiego/ovs-lab#1]
Hi  installing vagrant, vbox and vagrant-vbguest plugin, on running "vagrant up", I'm getting the following error:

Bringing machine 'internet' up with 'virtualbox' provider...
Bringing machine 'server1' up with 'virtualbox' provider...
Bringing machine 'server2' up with 'virtualbox' provider...
==> internet: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    internet: Box Provider: virtualbox
    internet: Box Version: >= 0
The executable 'curl' Vagrant is trying to run was not
found in the %PATH% variable. This is an error. Please verify
this software is installed and on the path.

I tried adding the curl.exe path to PATH variable, but it is still not working. Please help

**Comment by relaxdiego** [comment]
Hi @karanrajsingh. Thanks for trying out ovs-lab. The error that you're experiencing is specific to Vagrant. Please contact the Vagrant project maintainers instead at https://github.com/mitchellh/vagrant/issues. A quick search in that project revealed a similar error but with a different executable: https://github.com/mitchellh/vagrant/issues/3674

**Comment by karanrajsingh** [comment]
Thanks mark!

**Comment by relaxdiego** [comment]
No worries!
